import logging
import os
import pandas as pd
import google.generativeai as genai

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)


def generate_rca_report(backtest_metrics: dict, latest_regime: str) -> str:
    """Generates an AI RCA (Root Cause Analysis) briefing and diagnostic narrative

    by invoking the Gemini API using backtest performance metrics, market regime,
    and external prompt templates.

    Args:
        backtest_metrics (dict): Dictionary containing strategy performance metrics.
        latest_regime (str): Current market regime (e.g., 'Risk-On' or 'Risk-Off').

    Returns:
        str: Diagnostic RCA briefing text generated by Gemini or fallback template.
    """
    logger.info("Generating AI RCA diagnostic briefing via Gemini API.")

    cum_ret = backtest_metrics.get("cumulative_return", 0.0)
    mdd = backtest_metrics.get("max_drawdown", 0.0)
    win_rate = backtest_metrics.get("win_rate", 0.0)

    # Load prompt templates from external files for clean maintenance
    prompt_template_path = "templates/rca_prompt_template.txt"
    fallback_template_path = "templates/rca_fallback_template.txt"

    def load_fallback_template():
        if os.path.exists(fallback_template_path):
            with open(fallback_template_path, "r", encoding="utf-8") as f:
                fallback_template = f.read()
            return fallback_template.format(
                latest_regime=latest_regime,
                cum_ret=cum_ret,
                mdd=mdd,
                win_rate=win_rate
            )
        raise FileNotFoundError(
            f"Fallback template not found at {fallback_template_path}."
        )

    # Configure Gemini API key from environment variable
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        logger.warning("GEMINI_API_KEY environment variable not found. Using external fallback template.")
        return load_fallback_template()

    if not os.path.exists(prompt_template_path):
        raise FileNotFoundError(
            f"Required prompt template not found at {prompt_template_path}. Please ensure the template file exists."
        )

    with open(prompt_template_path, "r", encoding="utf-8") as f:
        prompt_template = f.read()

    prompt = prompt_template.format(
        latest_regime=latest_regime,
        cum_ret=cum_ret,
        mdd=mdd,
        win_rate=win_rate
    )

    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-1.5-flash")

        response = model.generate_content(prompt)
        briefing = response.text.strip()
        logger.info("Successfully generated RCA briefing from Gemini API.")
        return briefing

    except Exception as e:
        logger.error(f"Failed to generate RCA briefing from Gemini API: {e}")
        return load_fallback_template()


def generate_html_report(
    signaled_df: pd.DataFrame, timestamp: str, rca_briefing: str
) -> str:
    """Assembles and saves the final HTML daily intelligence card report into

    the history directory and syncs it to root index.html using an external template file.

    Args:
        signaled_df (pd.DataFrame): DataFrame with signal and asset weights.
        timestamp (str): Execution timestamp string.
        rca_briefing (str): AI RCA diagnostic text.

    Returns:
        str: Generated filename.
    """
    logger.info("Assembling HTML report card using external template.")

    os.makedirs("history", exist_ok=True)
    template_path = "templates/quant_report_template.html"

    date_str = timestamp.split(" ")[0]
    filename = f"history/{date_str}_quant_report.html"

    # Latest metrics from dataframe
    latest_regime = (
        signaled_df["Regime"].iloc[-1]
        if "Regime" in signaled_df.columns
        else "Risk-On"
    )
    latest_equity = (
        int(signaled_df["Target_Equity"].iloc[-1] * 100)
        if "Target_Equity" in signaled_df.columns
        else 50
    )
    latest_cash = 100 - latest_equity
    latest_action = (
        signaled_df["Action"].iloc[-1]
        if "Action" in signaled_df.columns
        else "Hold"
    )

    if not os.path.exists(template_path):
        raise FileNotFoundError(
            f"Required HTML template not found at {template_path}. Please ensure the template file exists."
        )

    with open(template_path, "r", encoding="utf-8") as f:
        template_content = f.read()

    html_content = template_content.format(
        date_str=date_str,
        timestamp=timestamp,
        latest_regime=latest_regime,
        latest_equity=latest_equity,
        latest_cash=latest_cash,
        latest_action=latest_action,
        rca_briefing=rca_briefing,
    )

    # 1. Save to history archive
    with open(filename, "w", encoding="utf-8") as f:
        f.write(html_content)

    # 2. Sync to root index.html so GitHub Pages displays it immediately
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(html_content)

    abs_path = os.path.abspath(filename)
    logger.info(f"HTML report successfully generated, saved to {abs_path}, and synced to root index.html")
    return filename
